-- 007_short_links_opt_outs.sql
-- קישורים אישיים קצרים, הסרה גלובלית מרשימת תפוצה ומעקב אידמפוטנטי
-- אחר מנות שליחה. מיועד לקמפיינים גדולים המגיעים מהדשבורד במנות של 500.

begin;

-- pgcrypto lives in the `extensions` schema on Supabase; ensure it exists and is
-- reachable by the RPCs (their search_path includes `extensions`).
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ═══════════ 1. הרחבת רשומת הקמפיין לריצה רב-מנתית אחת ═══════════

alter table public.sms_campaigns add column if not exists client_campaign_id uuid;
alter table public.sms_campaigns add column if not exists recipient_count integer not null default 0;
alter table public.sms_campaigns add column if not exists skipped_count integer not null default 0;
alter table public.sms_campaigns add column if not exists opt_out_count integer not null default 0;
alter table public.sms_campaigns add column if not exists failed_count integer not null default 0;
alter table public.sms_campaigns add column if not exists completed_batches integer not null default 0;
alter table public.sms_campaigns add column if not exists total_batches integer not null default 0;
alter table public.sms_campaigns add column if not exists last_error text;

-- PostgreSQL מאפשר כמה NULL-ים באינדקס unique; כל ריצה חדשה כן מקבלת UUID.
create unique index if not exists sms_campaigns_client_campaign_id_uidx
  on public.sms_campaigns (client_campaign_id);

-- ═══════════ 2. מנות שליחה — מניעת שליחה כפולה והתאוששות ═══════════

create table if not exists public.sms_campaign_batches (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.sms_campaigns(id) on delete cascade,
  client_campaign_id uuid not null,
  chunk_index integer not null check (chunk_index >= 0),
  recipient_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  skipped_count integer not null default 0,
  opt_out_count integer not null default 0,
  status text not null default 'processing',
  attempts integer not null default 1,
  inforu_request_id text,
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  unique (client_campaign_id, chunk_index)
);
create index if not exists sms_campaign_batches_campaign_idx
  on public.sms_campaign_batches (campaign_id, chunk_index);

-- ═══════════ 3. קישורים אישיים קצרים ═══════════

create table if not exists public.sms_short_links (
  token text primary key check (token ~ '^[A-Za-z0-9_-]{10,16}$'),
  phone text not null check (phone ~ '^9725[0-9]{8}$'),
  name text,
  campaign_id bigint not null references public.sms_campaigns(id) on delete cascade,
  campaign_name text not null,
  click_count integer not null default 0,
  created_at timestamptz not null default now(),
  last_resolved_at timestamptz,
  opted_out_at timestamptz,
  unique (campaign_id, phone)
);
create index if not exists sms_short_links_phone_idx on public.sms_short_links (phone);
create index if not exists sms_short_links_campaign_idx on public.sms_short_links (campaign_id);

-- ═══════════ 4. רשימת הסרה גלובלית ═══════════

create table if not exists public.sms_opt_outs (
  phone text primary key check (phone ~ '^9725[0-9]{8}$'),
  campaign_id bigint references public.sms_campaigns(id) on delete set null,
  campaign_name text,
  short_link_token text,
  source text not null default 'web_funnel',
  user_agent text,
  opted_out_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sms_opt_outs_time_idx on public.sms_opt_outs (opted_out_at desc);

alter table public.sms_campaign_batches enable row level security;
alter table public.sms_short_links enable row level security;
alter table public.sms_opt_outs enable row level security;

create index if not exists sms_clicks_campaign_id_idx on public.sms_clicks (campaign_id);
create index if not exists leads_source_phone_idx on public.leads (source, phone);

-- אגרגציה ב-DB מונעת חיתוך שקט של PostgREST אחרי 1,000 קליקים.
create or replace view public.sms_campaign_stats as
with click_stats as (
  select campaign_id, count(*)::bigint as clicks,
         count(distinct phone)::bigint as unique_clickers
  from public.sms_clicks
  where campaign_id is not null
  group by campaign_id
), lead_stats as (
  select x.campaign_id, count(distinct l.phone)::bigint as leads
  from (
    select distinct campaign_id, phone
    from public.sms_clicks
    where campaign_id is not null and phone is not null
  ) x
  join public.leads l on l.phone = x.phone and l.source = 'web_funnel'
  group by x.campaign_id
)
select c.*,
       coalesce(cs.clicks, 0) as clicks,
       coalesce(cs.unique_clickers, 0) as unique_clickers,
       coalesce(ls.leads, 0) as leads
from public.sms_campaigns c
left join click_stats cs on cs.campaign_id = c.id
left join lead_stats ls on ls.campaign_id = c.id;

grant select on public.sms_campaign_stats to service_role;

-- ═══════════ 5. יצירה/איתור של ריצת קמפיין אחת ═══════════

create or replace function public.register_sms_campaign(
  p_client_campaign_id uuid,
  p_campaign_name text,
  p_message text,
  p_sender text,
  p_recipient_count integer,
  p_total_batches integer
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if p_client_campaign_id is null then raise exception 'missing campaign id'; end if;

  insert into public.sms_campaigns (
    client_campaign_id, campaign_name, message_template, link_mode, sender,
    recipient_count, total_batches, status, created_at, updated_at
  ) values (
    p_client_campaign_id,
    left(coalesce(nullif(trim(p_campaign_name), ''), 'campaign'), 200),
    left(coalesce(p_message, ''), 4000),
    'token',
    left(coalesce(nullif(trim(p_sender), ''), 'nahman'), 100),
    greatest(coalesce(p_recipient_count, 0), 0),
    greatest(coalesce(p_total_batches, 0), 0),
    'preparing', now(), now()
  )
  on conflict (client_campaign_id) do update set
    campaign_name = excluded.campaign_name,
    message_template = excluded.message_template,
    link_mode = 'token',
    sender = excluded.sender,
    recipient_count = greatest(public.sms_campaigns.recipient_count, excluded.recipient_count),
    total_batches = greatest(public.sms_campaigns.total_batches, excluded.total_batches),
    updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

-- תופס מנה רק פעם אחת. מנה שנדחתה מפורשות על-ידי הספק ניתנת לניסיון חוזר;
-- מנה שנמצאת במצב sent/unknown לא תישלח אוטומטית שוב.
create or replace function public.claim_sms_campaign_batch(
  p_client_campaign_id uuid,
  p_chunk_index integer,
  p_recipient_count integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id bigint;
  v_batch public.sms_campaign_batches%rowtype;
  v_inserted_id bigint;
begin
  select id into v_campaign_id
  from public.sms_campaigns
  where client_campaign_id = p_client_campaign_id;

  if v_campaign_id is null then
    return jsonb_build_object('claimed', false, 'reason', 'campaign_not_found');
  end if;

  insert into public.sms_campaign_batches (
    campaign_id, client_campaign_id, chunk_index, recipient_count, status
  ) values (
    v_campaign_id, p_client_campaign_id, greatest(p_chunk_index, 0),
    greatest(coalesce(p_recipient_count, 0), 0), 'processing'
  )
  on conflict (client_campaign_id, chunk_index) do nothing
  returning id into v_inserted_id;

  if v_inserted_id is not null then
    update public.sms_campaigns
       set status = 'sending', updated_at = now()
     where id = v_campaign_id and status not in ('sent', 'partial', 'attention');
    return jsonb_build_object('claimed', true, 'campaign_id', v_campaign_id, 'batch_id', v_inserted_id);
  end if;

  select * into v_batch
  from public.sms_campaign_batches
  where client_campaign_id = p_client_campaign_id and chunk_index = p_chunk_index
  for update;

  if v_batch.status = 'rejected' and v_batch.attempts < 3 then
    update public.sms_campaign_batches
       set status = 'processing', attempts = attempts + 1, error = null,
           started_at = now(), finished_at = null
     where id = v_batch.id;
    return jsonb_build_object('claimed', true, 'campaign_id', v_campaign_id,
      'batch_id', v_batch.id, 'retry', true);
  end if;

  if v_batch.status = 'processing' and v_batch.started_at < now() - interval '10 minutes' then
    update public.sms_campaign_batches
       set status = 'unknown', error = coalesce(error, 'stale processing state'), finished_at = now()
     where id = v_batch.id;
    update public.sms_campaigns
       set status = 'attention', last_error = 'מנה נשארה במצב לא ודאי', updated_at = now()
     where id = v_campaign_id;
    v_batch.status := 'unknown';
  end if;

  return jsonb_build_object(
    'claimed', false,
    'reason', case when v_batch.status = 'sent' then 'already_sent' else v_batch.status end,
    'campaign_id', v_campaign_id,
    'batch_id', v_batch.id,
    'sent', v_batch.sent_count,
    'failed', v_batch.failed_count,
    'skipped', v_batch.skipped_count,
    'optedOut', v_batch.opt_out_count
  );
end;
$$;

-- ═══════════ 6. הכנת אסימונים וסינון הסרות במנה אחת בתוך DB ═══════════

create or replace function public.prepare_sms_batch(
  p_campaign_id bigint,
  p_campaign_name text,
  p_recipients jsonb
)
returns table(out_phone text, out_name text, out_token text, out_opted_out boolean)
language plpgsql
security definer
-- `extensions` is required so pgcrypto's gen_random_bytes() (used to mint tokens)
-- resolves on Supabase, where pgcrypto is installed in the extensions schema.
set search_path = public, extensions
as $$
declare
  r jsonb;
  v_phone text;
  v_name text;
  v_token text;
  v_opted boolean;
  v_seen text[] := '{}'::text[];
begin
  if jsonb_typeof(coalesce(p_recipients, '[]'::jsonb)) <> 'array' then
    raise exception 'recipients must be an array';
  end if;

  for r in select value from jsonb_array_elements(coalesce(p_recipients, '[]'::jsonb)) loop
    v_phone := regexp_replace(coalesce(r->>'phone', ''), '\D', '', 'g');
    if v_phone like '0%' then v_phone := '972' || substr(v_phone, 2); end if;
    if v_phone !~ '^9725[0-9]{8}$' then continue; end if;
    if v_phone = any(v_seen) then continue; end if;
    v_seen := array_append(v_seen, v_phone);
    v_name := nullif(left(trim(coalesce(r->>'name', '')), 200), '');

    select exists(select 1 from public.sms_opt_outs o where o.phone = v_phone)
      into v_opted;

    if v_opted then
      out_phone := v_phone;
      out_name := v_name;
      out_token := null;
      out_opted_out := true;
      return next;
      continue;
    end if;

    select l.token into v_token
    from public.sms_short_links l
    where l.campaign_id = p_campaign_id and l.phone = v_phone;

    if v_token is null then
      loop
        -- 7 בתים הופכים לאסימון base64url בן 10 תווים (ללא padding).
        v_token := rtrim(translate(encode(gen_random_bytes(7), 'base64'), '+/', '-_'), '=');
        begin
          insert into public.sms_short_links (token, phone, name, campaign_id, campaign_name)
          values (v_token, v_phone, v_name, p_campaign_id,
                  left(coalesce(nullif(trim(p_campaign_name), ''), 'campaign'), 200));
          exit;
        exception when unique_violation then
          select l.token into v_token
          from public.sms_short_links l
          where l.campaign_id = p_campaign_id and l.phone = v_phone;
          if v_token is not null then exit; end if;
        end;
      end loop;
    elsif v_name is not null then
      update public.sms_short_links set name = v_name
      where token = v_token and name is distinct from v_name;
    end if;

    out_phone := v_phone;
    out_name := v_name;
    out_token := v_token;
    out_opted_out := false;
    return next;
  end loop;
end;
$$;

-- ═══════════ 7. פתרון אסימון ולוג קליק מהדפדפן ═══════════

create or replace function public.resolve_sms_short_link(
  p_token text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_link public.sms_short_links%rowtype;
  v_opted boolean;
begin
  if coalesce(trim(p_token), '') !~ '^[A-Za-z0-9_-]{10,16}$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_token');
  end if;

  update public.sms_short_links
     set click_count = click_count + 1, last_resolved_at = now()
   where token = trim(p_token)
   returning * into v_link;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  insert into public.sms_clicks (campaign_id, campaign_name, phone, user_agent, clicked_at)
  values (v_link.campaign_id, v_link.campaign_name, v_link.phone,
          left(coalesce(p_user_agent, ''), 500), now());

  select exists(select 1 from public.sms_opt_outs o where o.phone = v_link.phone)
    into v_opted;

  return jsonb_build_object(
    'ok', true,
    'phone', v_link.phone,
    'name', v_link.name,
    'campaign', v_link.campaign_name,
    'optedOut', v_opted
  );
end;
$$;

-- ═══════════ 8. הסרה אמיתית לפי האסימון האישי ═══════════

create or replace function public.opt_out_sms(
  p_token text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_link public.sms_short_links%rowtype;
begin
  select * into v_link
  from public.sms_short_links
  where token = trim(coalesce(p_token, ''));

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'invalid_token');
  end if;

  insert into public.sms_opt_outs (
    phone, campaign_id, campaign_name, short_link_token, source, user_agent,
    opted_out_at, updated_at
  ) values (
    v_link.phone, v_link.campaign_id, v_link.campaign_name, v_link.token,
    'web_funnel', left(coalesce(p_user_agent, ''), 500), now(), now()
  )
  on conflict (phone) do update set
    campaign_id = excluded.campaign_id,
    campaign_name = excluded.campaign_name,
    short_link_token = excluded.short_link_token,
    source = excluded.source,
    user_agent = excluded.user_agent,
    updated_at = now();

  update public.sms_short_links set opted_out_at = now() where phone = v_link.phone;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.opt_out_sms_by_phone(
  p_phone text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phone text;
begin
  v_phone := regexp_replace(coalesce(p_phone, ''), '\D', '', 'g');
  if v_phone like '0%' then v_phone := '972' || substr(v_phone, 2); end if;
  if v_phone !~ '^9725[0-9]{8}$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_phone');
  end if;

  insert into public.sms_opt_outs (
    phone, source, user_agent, opted_out_at, updated_at
  ) values (
    v_phone, 'web_funnel_manual', left(coalesce(p_user_agent, ''), 500), now(), now()
  )
  on conflict (phone) do update set
    source = excluded.source,
    user_agent = excluded.user_agent,
    updated_at = now();

  update public.sms_short_links set opted_out_at = now() where phone = v_phone;
  return jsonb_build_object('ok', true);
end;
$$;

-- ═══════════ 9. לידים לפי קמפיין בלי מגבלת רשימת IN ═══════════

create or replace function public.admin_campaign_leads(
  p_campaign_name text,
  p_limit integer default 300,
  p_offset integer default 0
)
returns setof public.leads
language sql
stable
security definer
set search_path = public
as $$
  select l.*
  from public.leads l
  where l.source = 'web_funnel'
    and exists (
      select 1
      from public.sms_clicks sc
      where sc.campaign_name = p_campaign_name and sc.phone = l.phone
    )
  order by l.created_at desc
  limit least(greatest(coalesce(p_limit, 300), 1), 1000)
  offset greatest(coalesce(p_offset, 0), 0)
$$;

revoke all on function public.admin_campaign_leads(text,integer,integer) from public, anon, authenticated;
grant execute on function public.admin_campaign_leads(text,integer,integer) to service_role;

-- ═══════════ 10. סיום מנה וחישוב מונה קמפיין אטומי ═══════════

create or replace function public.finish_sms_campaign_batch(
  p_client_campaign_id uuid,
  p_chunk_index integer,
  p_status text,
  p_sent integer default 0,
  p_failed integer default 0,
  p_skipped integer default 0,
  p_opted_out integer default 0,
  p_request_id text default null,
  p_error text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id bigint;
  v_sent integer;
  v_failed integer;
  v_skipped integer;
  v_opted integer;
  v_finished integer;
  v_unknown integer;
  v_processing integer;
  v_total integer;
  v_status text;
begin
  select id, total_batches into v_campaign_id, v_total
  from public.sms_campaigns where client_campaign_id = p_client_campaign_id
  for update;

  if v_campaign_id is null then
    return jsonb_build_object('ok', false, 'reason', 'campaign_not_found');
  end if;

  update public.sms_campaign_batches set
    status = case when p_status in ('sent','rejected','unknown') then p_status else 'unknown' end,
    sent_count = greatest(coalesce(p_sent, 0), 0),
    failed_count = greatest(coalesce(p_failed, 0), 0),
    skipped_count = greatest(coalesce(p_skipped, 0), 0),
    opt_out_count = greatest(coalesce(p_opted_out, 0), 0),
    inforu_request_id = nullif(left(coalesce(p_request_id, ''), 500), ''),
    error = nullif(left(coalesce(p_error, ''), 2000), ''),
    finished_at = now()
  where client_campaign_id = p_client_campaign_id and chunk_index = p_chunk_index;

  select
    coalesce(sum(sent_count), 0)::integer,
    coalesce(sum(failed_count), 0)::integer,
    coalesce(sum(skipped_count), 0)::integer,
    coalesce(sum(opt_out_count), 0)::integer,
    count(*) filter (where status in ('sent','rejected','unknown'))::integer,
    count(*) filter (where status = 'unknown')::integer,
    count(*) filter (where status = 'processing')::integer
  into v_sent, v_failed, v_skipped, v_opted, v_finished, v_unknown, v_processing
  from public.sms_campaign_batches
  where campaign_id = v_campaign_id;

  v_status := case
    when v_unknown > 0 then 'attention'
    when v_finished >= v_total and v_total > 0 and v_failed = 0 then 'sent'
    when v_finished >= v_total and v_total > 0 then 'partial'
    when v_processing > 0 or v_finished > 0 then 'sending'
    else 'preparing'
  end;

  update public.sms_campaigns set
    sent_count = v_sent,
    failed_count = v_failed,
    skipped_count = v_skipped,
    opt_out_count = v_opted,
    completed_batches = v_finished,
    status = v_status,
    inforu_request_id = coalesce(nullif(left(coalesce(p_request_id, ''), 500), ''), inforu_request_id),
    last_error = nullif(left(coalesce(p_error, ''), 2000), ''),
    updated_at = now()
  where id = v_campaign_id;

  return jsonb_build_object(
    'ok', true, 'campaignId', v_campaign_id, 'status', v_status,
    'sent', v_sent, 'failed', v_failed, 'skipped', v_skipped,
    'optedOut', v_opted, 'completedBatches', v_finished, 'totalBatches', v_total
  );
end;
$$;

-- ברירת המחדל של PostgreSQL מעניקה EXECUTE ל-PUBLIC; מצמצמים במפורש.
revoke all on function public.register_sms_campaign(uuid,text,text,text,integer,integer) from public, anon, authenticated;
revoke all on function public.claim_sms_campaign_batch(uuid,integer,integer) from public, anon, authenticated;
revoke all on function public.prepare_sms_batch(bigint,text,jsonb) from public, anon, authenticated;
revoke all on function public.finish_sms_campaign_batch(uuid,integer,text,integer,integer,integer,integer,text,text) from public, anon, authenticated;

grant execute on function public.register_sms_campaign(uuid,text,text,text,integer,integer) to service_role;
grant execute on function public.claim_sms_campaign_batch(uuid,integer,integer) to service_role;
grant execute on function public.prepare_sms_batch(bigint,text,jsonb) to service_role;
grant execute on function public.finish_sms_campaign_batch(uuid,integer,text,integer,integer,integer,integer,text,text) to service_role;

revoke all on function public.resolve_sms_short_link(text,text) from public;
revoke all on function public.opt_out_sms(text,text) from public;
revoke all on function public.opt_out_sms_by_phone(text,text) from public;
grant execute on function public.resolve_sms_short_link(text,text) to anon, authenticated;
grant execute on function public.opt_out_sms(text,text) to anon, authenticated;
grant execute on function public.opt_out_sms_by_phone(text,text) to anon, authenticated;

commit;
